services:
  mirrord:
    build: .
    image: mirrord
    container_name: mirrord
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./mirrors:/data
      - mirrord_db:/tmp/mirrord

volumes:
  mirrord_db:
