services:
  mirrord:
    image: ghcr.io/nemvince/mirrord:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data/lock:/var/lib/mirrord/lock
      - ./data/mirrord.db:/var/lib/mirrord/mirrord.db
      - ./data/mirrors:/mirrors

volumes:
  mirrord_db:
