services:
  mirrord:
    build: .
    image: mirrord
    container_name: mirrord
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data/lock:/var/lib/mirrord/lock
      - ./data/mirrord.db:/var/lib/mirrord/mirrord.db
      - ./data/mirrors:/mirrors

volumes:
  mirrord_db:
